---@class Object.Ability
---施法打断范围
---
---当技能施法开始或施法出手阶段结束时，如果与施法目标的距离超过该值，会打断技能释放。
---@field ability_break_cast_range string[]
---建造方式
---@field ability_build_subtype any
---施法完成
---
---施法完成时长（也可以叫做技能后摇）
---@field ability_bw_point number
---施法开始
---
---施法开始时长（也可以叫做技能前摇）
---@field ability_cast_point number
---释放范围
---
---以角色为圆心，以该值为半径的圆形区域。是角色不需要移动即可释放技能的最远距离。
---@field ability_cast_range string[]
---技能释放类型
---
---技能的释放类型。
---@field ability_cast_type any
---施法出手
---
---施法出手时长
---@field ability_channel_time number
---技能消耗
---
---释放技能消耗的MP(会根据单位自身的技能资源进行变化)数值
---@field ability_cost string[]
---技能伤害值
---
---技能造成的伤害，可使用公式编辑，需在触发内引用才可生效
---@field ability_damage string[]
---技能影响范围
---
---当前技能的影响范围，
---@field ability_damage_range string[]
---生命值消耗
---
---使用该技能时会消耗的生命值
---@field ability_hp_cost string[]
---图标
---
---技能的图标，会在编辑器和游戏的ui上显示
---@field ability_icon any
---摇杆指示器索敌范围
---@field ability_joystick_check_range number
---技能最大等级
---
---技能的等级上限
---@field ability_max_level number
---最大充能数
---
---技能的最大充能数，必须满足充能数大于0且不在冷却状态才能施放该技能
---@field ability_max_stack_count string[]
---施法引导
---
---施法引导时长
---@field ability_prepare_time number
---充能时间
---
---每增加一层充能数所需的时间（单位为秒）
---@field ability_stack_cd string[]
---技能阶段配置
---@field ability_stage_config any
---技能绑定动画轨
---@field ability_timeline_resource any
---长度
---
---箭头指示器的长度
---@field arrow_length string[]
---宽度
---
---箭头指示器的宽度
---@field arrow_width string[]
---编辑技能效果
---@field art_resource_btn any
---自动拾取
---
---当采集到的资源是物品时，是否自动将物品拾取。如果不自动拾取则物品会创建在地面。
---@field auto_pick boolean
---后摇特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field bs_sfx_list any[]
---后摇音效
---@field bs_sound_effect any[]
---建造单位
---
---建造技能建造的单位类型
---@field build_list any[]
---建造角度
---@field build_rotate number
---攻击范围预览特效
---
---攻击范围预览的特效，大小参考ID为101492的特效资源
---@field building_attack_range_sfx any
---敌人
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_enemy number
---队友
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_friend number
---中立
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_neutral number
---己方
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_self number
---攻击命令触发自动施法
---
---勾选后攻击命令能触发自动施法。
---@field can_autocast_when_attack_target boolean
---施法完成可以被打断
---
---技能施法完成阶段能否被其他技能或者移动打断
---@field can_bs_interrupt boolean
---可以缓存
---
---开启时，被控制时，控制结束 依旧可以继续释放（例如被禁止施法时发布施放命令，禁止施法解除后就会自动施放出来）
---@field can_cache boolean
---施法出手可以被打断
---
---技能施法出手阶段能否被其他技能或者移动打断
---@field can_cast_interrupt boolean
---生命不足能否施放
---
---如果单位当前生命值不满足消耗时，能否施放技能
---@field can_cast_when_hp_insufficient boolean
---消耗生命值施放
---
---开启后可以配置消耗生命值相关的技能参数。如无需要请勿开启该配置，会增加系统消耗。
---@field can_cost_hp boolean
---技能可以打断其他技能
---
---释放该技能时候会尝试打断当前正在释放的技能
---@field can_interrupt_others boolean
---施法引导可以被打断
---
---技能施法引导阶段能否被其他技能或者移动打断
---@field can_prepare_interrupt boolean
---施法开始可以被打断
---
---技能施法开始阶段能否被其他技能或者移动打断
---@field can_ps_interrupt boolean
---圆形半径
---
---圆形指示器的半径
---@field circle_radius string[]
---冷却时间
---
---技能的冷却时间，释放一次技能后需要等待该时间才可继续释放（单位为秒）
---@field cold_down_time string[]
---采集动画
---
---使用采集技能时会播放的动画。会在技能施法开始时播放，施法停止时停止。
---@field collection_animation string
---循环播放动画
---
---采集技能时播放的采集动画是否会循环播放。
---@field collection_animation_loop boolean
---连续施法
---
---是否在采集完成后继续采集（仅在技能冷却时间为0时生效）
---@field collection_continuously boolean
---可破坏物标签要求
---
---技能索敌时只会搜索带有指定标签的可破坏物
---@field collection_destructible_tags any
---消耗生命是否致死
---
---如果单位当前生命值不满足消耗时施放技能，则该项为true时单位会死亡，为false时会保留1点生命值
---@field cost_hp_can_die boolean
---施法特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field cst_sfx_list any[]
---施法音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field cst_sound_effect any[]
---自定义特效选择
---@field customized_pointer_sfx any
---描述
---
---技能的介绍说明，用在编辑器内和游戏内的Tips显示上
---@field description string
---自定义指示器特效
---@field enable_customized_pointer_sfx boolean
---结束特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field end_sfx_list any[]
---结束音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field end_sound_effect any[]
---阵营
---
---按阵营选取目标。
---@field filter_condition_camp any
---单位移动类型
---
---技能索敌时只会搜索指定移动类型的单位
---@field filter_condition_move_channel_type any
---类型
---
---按种类选取目标。
---@field filter_condition_type any
---物品标签要求
---
---技能索敌时只会搜索带有指定标签的物品
---@field filter_item_tags any
---单位标签要求
---
---技能索敌时只会搜索带有指定标签的单位
---@field filter_unit_tags any
---单位排除标签
---
---技能索敌时不会搜索带有指定标签的单位
---@field forbid_unit_tags any
---受击特效
---
---技能命中时，在命中目标处显示的特效
---@field hit_sfx_list any[]
---击中音效
---
---技能命中时，会在命中者处播放的音效内容
---@field hit_sound_effect any[]
---技能受冷却影响
---
---技能受到单位属性中的冷却缩短的影响
---@field influenced_by_cd_reduce boolean
---移动会对技能产生影响
---
---勾选后移动会尝试打断当前技能，不勾选则可以实现移动施法
---@field influenced_by_move boolean
---自动施法
---
---优先按照阵营选取目标，其次按类别，如果都相同，则距离近优先。
---@field is_autocast boolean
---是否为蓄力技能
---
---蓄力技能专属，为true时，引导时间会作为蓄力技能一阶段的引导时间。【施法开始阶段需要配置为0】
---@field is_charge_ability boolean
---立刻施法
---
---释放这个技能是否需要施法过程，开启时可以在单位存活的任何时期发动该技能，即使被禁止施法也可以正常释放。
---@field is_immediate any
---近战
---
---开启时，标记这个技能造成的伤害为近战伤害
---@field is_meele boolean
---ID
---
---技能的ID
---@field key number
---玩家自定义
---@field kv any
---魔法书技能
---
---魔法书中存放的技能list
---@field magicbook_list any[]
---名称
---
---当前技能的名称
---@field name string
---是否转身
---
---开启时，技能释放后单位会自动转到技能释放的方向（转身速度为单位的转身速度）
---@field need_turn_to_target boolean
---采集获得量
---
---每次使用采集技能时获取到的资源数量。如果采集的是玩家属性，则获得对应的玩家属性值，如果采集的是物品，则获得对应数量的物品。
---@field pick_count number
---玩家属性消耗
---
---施放技能消耗的玩家属性，技能拥有者的玩家该属性不足时无法施放技能
---@field player_props_cost any[]
---指示器可被阻挡
---@field pointer_can_block boolean
---指示器类型
---@field pointer_channel any
---被阻挡类型
---@field pointer_limitation any
---前置条件
---
---释放技能的前置条件
---@field precondition_list any[]
---前摇特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field ps_sfx_list any[]
---前摇音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field ps_sound_effect any[]
---可以超出范围施法
---
---如果技能目标点超出施法范围，会在施法范围内离目标最近的点施放
---@field release_immediately_out_of_range boolean
---允许学习等级
---
---单位学习该技能所需要的等级
---@field required_level any
---角度
---
---扇形指示器的角度
---@field sector_angle string[]
---扇形半径
---
---扇形指示器的边长
---@field sector_radius string[]
---攻击范围预览
---
---开启后，建造时的模型会附带攻击范围预览
---@field show_building_attack_range boolean
---指示器类型
---
---释放技能时的鼠标指示器的样式
---@field sight_type any
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list any[]
---显示准备倒计时
---
---开启时，会根据技能的施法时间显示相应的进度条
---@field sp_count_down boolean
---准备特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field sp_sfx_list any[]
---准备音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field sp_sound_effect any[]
---编辑器后缀
---
---只在编辑器中使用，用于区分相同名字的物品。并不会影响到游戏内的显示内容
---@field suffix string
---标签
---
---用于对技能的分类处理。为技能贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：所有拥有XX标签的技能等级+1
---@field tags any[]
---目标长度
---@field target_arrow_length string[]
---目标宽度
---@field target_arrow_width string[]
---特殊筛选
---
---配置技能索敌时的特殊筛选规则（如排除自己、允许无敌等）
---@field target_attribute any
---目标圆形半径
---@field target_circle_radius string[]
---目标角度
---@field target_sector_angle string[]
---目标扇形半径
---@field target_sector_radius string[]
---过渡时间
---@field transition_duration number
---过渡起始时间
---@field transition_start_time number
---建筑
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_building number
---生物
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_creature number
---可破坏物
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_destructible number
---英雄
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_hero number
---物品
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_item number
---UID
---
---技能的唯一id
---@field uid string

---@class Object.AbilityOptions
---施法打断范围
---
---当技能施法开始或施法出手阶段结束时，如果与施法目标的距离超过该值，会打断技能释放。
---@field ability_break_cast_range? string[]
---建造方式
---@field ability_build_subtype? any
---施法完成
---
---施法完成时长（也可以叫做技能后摇）
---@field ability_bw_point? number
---施法开始
---
---施法开始时长（也可以叫做技能前摇）
---@field ability_cast_point? number
---释放范围
---
---以角色为圆心，以该值为半径的圆形区域。是角色不需要移动即可释放技能的最远距离。
---@field ability_cast_range? string[]
---技能释放类型
---
---技能的释放类型。
---@field ability_cast_type? any
---施法出手
---
---施法出手时长
---@field ability_channel_time? number
---技能消耗
---
---释放技能消耗的MP(会根据单位自身的技能资源进行变化)数值
---@field ability_cost? string[]
---技能伤害值
---
---技能造成的伤害，可使用公式编辑，需在触发内引用才可生效
---@field ability_damage? string[]
---技能影响范围
---
---当前技能的影响范围，
---@field ability_damage_range? string[]
---生命值消耗
---
---使用该技能时会消耗的生命值
---@field ability_hp_cost? string[]
---图标
---
---技能的图标，会在编辑器和游戏的ui上显示
---@field ability_icon? any
---摇杆指示器索敌范围
---@field ability_joystick_check_range? number
---技能最大等级
---
---技能的等级上限
---@field ability_max_level? number
---最大充能数
---
---技能的最大充能数，必须满足充能数大于0且不在冷却状态才能施放该技能
---@field ability_max_stack_count? string[]
---施法引导
---
---施法引导时长
---@field ability_prepare_time? number
---充能时间
---
---每增加一层充能数所需的时间（单位为秒）
---@field ability_stack_cd? string[]
---技能阶段配置
---@field ability_stage_config? any
---技能绑定动画轨
---@field ability_timeline_resource? any
---长度
---
---箭头指示器的长度
---@field arrow_length? string[]
---宽度
---
---箭头指示器的宽度
---@field arrow_width? string[]
---编辑技能效果
---@field art_resource_btn? any
---自动拾取
---
---当采集到的资源是物品时，是否自动将物品拾取。如果不自动拾取则物品会创建在地面。
---@field auto_pick? boolean
---后摇特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field bs_sfx_list? any[]
---后摇音效
---@field bs_sound_effect? any[]
---建造单位
---
---建造技能建造的单位类型
---@field build_list? any[]
---建造角度
---@field build_rotate? number
---攻击范围预览特效
---
---攻击范围预览的特效，大小参考ID为101492的特效资源
---@field building_attack_range_sfx? any
---敌人
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_enemy? number
---队友
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_friend? number
---中立
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_neutral? number
---己方
---
---阵营值越小，优先级越高，如果阵营值相同，则距离近优先。
---@field camp_priority_self? number
---攻击命令触发自动施法
---
---勾选后攻击命令能触发自动施法。
---@field can_autocast_when_attack_target? boolean
---施法完成可以被打断
---
---技能施法完成阶段能否被其他技能或者移动打断
---@field can_bs_interrupt? boolean
---可以缓存
---
---开启时，被控制时，控制结束 依旧可以继续释放（例如被禁止施法时发布施放命令，禁止施法解除后就会自动施放出来）
---@field can_cache? boolean
---施法出手可以被打断
---
---技能施法出手阶段能否被其他技能或者移动打断
---@field can_cast_interrupt? boolean
---生命不足能否施放
---
---如果单位当前生命值不满足消耗时，能否施放技能
---@field can_cast_when_hp_insufficient? boolean
---消耗生命值施放
---
---开启后可以配置消耗生命值相关的技能参数。如无需要请勿开启该配置，会增加系统消耗。
---@field can_cost_hp? boolean
---技能可以打断其他技能
---
---释放该技能时候会尝试打断当前正在释放的技能
---@field can_interrupt_others? boolean
---施法引导可以被打断
---
---技能施法引导阶段能否被其他技能或者移动打断
---@field can_prepare_interrupt? boolean
---施法开始可以被打断
---
---技能施法开始阶段能否被其他技能或者移动打断
---@field can_ps_interrupt? boolean
---圆形半径
---
---圆形指示器的半径
---@field circle_radius? string[]
---冷却时间
---
---技能的冷却时间，释放一次技能后需要等待该时间才可继续释放（单位为秒）
---@field cold_down_time? string[]
---采集动画
---
---使用采集技能时会播放的动画。会在技能施法开始时播放，施法停止时停止。
---@field collection_animation? string
---循环播放动画
---
---采集技能时播放的采集动画是否会循环播放。
---@field collection_animation_loop? boolean
---连续施法
---
---是否在采集完成后继续采集（仅在技能冷却时间为0时生效）
---@field collection_continuously? boolean
---可破坏物标签要求
---
---技能索敌时只会搜索带有指定标签的可破坏物
---@field collection_destructible_tags? any
---消耗生命是否致死
---
---如果单位当前生命值不满足消耗时施放技能，则该项为true时单位会死亡，为false时会保留1点生命值
---@field cost_hp_can_die? boolean
---施法特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field cst_sfx_list? any[]
---施法音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field cst_sound_effect? any[]
---自定义特效选择
---@field customized_pointer_sfx? any
---描述
---
---技能的介绍说明，用在编辑器内和游戏内的Tips显示上
---@field description? string
---自定义指示器特效
---@field enable_customized_pointer_sfx? boolean
---结束特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field end_sfx_list? any[]
---结束音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field end_sound_effect? any[]
---阵营
---
---按阵营选取目标。
---@field filter_condition_camp? any
---单位移动类型
---
---技能索敌时只会搜索指定移动类型的单位
---@field filter_condition_move_channel_type? any
---类型
---
---按种类选取目标。
---@field filter_condition_type? any
---物品标签要求
---
---技能索敌时只会搜索带有指定标签的物品
---@field filter_item_tags? any
---单位标签要求
---
---技能索敌时只会搜索带有指定标签的单位
---@field filter_unit_tags? any
---单位排除标签
---
---技能索敌时不会搜索带有指定标签的单位
---@field forbid_unit_tags? any
---受击特效
---
---技能命中时，在命中目标处显示的特效
---@field hit_sfx_list? any[]
---击中音效
---
---技能命中时，会在命中者处播放的音效内容
---@field hit_sound_effect? any[]
---技能受冷却影响
---
---技能受到单位属性中的冷却缩短的影响
---@field influenced_by_cd_reduce? boolean
---移动会对技能产生影响
---
---勾选后移动会尝试打断当前技能，不勾选则可以实现移动施法
---@field influenced_by_move? boolean
---自动施法
---
---优先按照阵营选取目标，其次按类别，如果都相同，则距离近优先。
---@field is_autocast? boolean
---是否为蓄力技能
---
---蓄力技能专属，为true时，引导时间会作为蓄力技能一阶段的引导时间。【施法开始阶段需要配置为0】
---@field is_charge_ability? boolean
---立刻施法
---
---释放这个技能是否需要施法过程，开启时可以在单位存活的任何时期发动该技能，即使被禁止施法也可以正常释放。
---@field is_immediate? any
---近战
---
---开启时，标记这个技能造成的伤害为近战伤害
---@field is_meele? boolean
---ID
---
---技能的ID
---@field key? number
---玩家自定义
---@field kv? any
---魔法书技能
---
---魔法书中存放的技能list
---@field magicbook_list? any[]
---名称
---
---当前技能的名称
---@field name? string
---是否转身
---
---开启时，技能释放后单位会自动转到技能释放的方向（转身速度为单位的转身速度）
---@field need_turn_to_target? boolean
---采集获得量
---
---每次使用采集技能时获取到的资源数量。如果采集的是玩家属性，则获得对应的玩家属性值，如果采集的是物品，则获得对应数量的物品。
---@field pick_count? number
---玩家属性消耗
---
---施放技能消耗的玩家属性，技能拥有者的玩家该属性不足时无法施放技能
---@field player_props_cost? any[]
---指示器可被阻挡
---@field pointer_can_block? boolean
---指示器类型
---@field pointer_channel? any
---被阻挡类型
---@field pointer_limitation? any
---前置条件
---
---释放技能的前置条件
---@field precondition_list? any[]
---前摇特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field ps_sfx_list? any[]
---前摇音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field ps_sound_effect? any[]
---可以超出范围施法
---
---如果技能目标点超出施法范围，会在施法范围内离目标最近的点施放
---@field release_immediately_out_of_range? boolean
---允许学习等级
---
---单位学习该技能所需要的等级
---@field required_level? any
---角度
---
---扇形指示器的角度
---@field sector_angle? string[]
---扇形半径
---
---扇形指示器的边长
---@field sector_radius? string[]
---攻击范围预览
---
---开启后，建造时的模型会附带攻击范围预览
---@field show_building_attack_range? boolean
---指示器类型
---
---释放技能时的鼠标指示器的样式
---@field sight_type? any
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list? any[]
---显示准备倒计时
---
---开启时，会根据技能的施法时间显示相应的进度条
---@field sp_count_down? boolean
---准备特效
---
---技能执行到该阶段时，在自身处显示的特效，技能被打断后会立即停止该特效
---@field sp_sfx_list? any[]
---准备音效
---
---技能执行到该阶段时，在自身处播放的音效内容，技能被打断后会立即停止该音效
---@field sp_sound_effect? any[]
---编辑器后缀
---
---只在编辑器中使用，用于区分相同名字的物品。并不会影响到游戏内的显示内容
---@field suffix? string
---标签
---
---用于对技能的分类处理。为技能贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：所有拥有XX标签的技能等级+1
---@field tags? any[]
---目标长度
---@field target_arrow_length? string[]
---目标宽度
---@field target_arrow_width? string[]
---特殊筛选
---
---配置技能索敌时的特殊筛选规则（如排除自己、允许无敌等）
---@field target_attribute? any
---目标圆形半径
---@field target_circle_radius? string[]
---目标角度
---@field target_sector_angle? string[]
---目标扇形半径
---@field target_sector_radius? string[]
---过渡时间
---@field transition_duration? number
---过渡起始时间
---@field transition_start_time? number
---建筑
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_building? number
---生物
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_creature? number
---可破坏物
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_destructible? number
---英雄
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_hero? number
---物品
---
---类别值越小，优先级越高，如果类别值相同，则距离近优先。
---@field type_priority_item? number
---UID
---
---技能的唯一id
---@field uid? string

---@class Object.Buff
---最大持续时间
---@field attach_model_list any
---循环周期
---
---每隔多长时间触发一次循环周期到期事件
---@field cycle_time number
---描述
---@field description string
---是否死亡时消失
---
---死亡时是否销毁这个魔法效果。永久型的魔法效果不要勾选该选项。
---@field disappear_when_dead boolean
---最大持续时间
---@field get_effect_list any
---光环效果
---
---光环会对附近符合条件的单位添加该光环效果
---@field halo_effect any
---不影响单位标签
---
---不会对拥有指定标签的单位施加光环效果。
---只有满足所有判断条件时，单位才会获得光环效果。
---@field ign_inf_unit_tag any[]
---不影响单位类型
---
---不会对指定类型的单位施加光环效果。
---只有满足所有判断条件时，单位才会获得光环效果。
---@field ign_inf_unit_type any
---影响单位标签
---
---会对拥有指定标签的单位施加光环效果。
---只有满足所有判断条件时，单位才会获得光环效果。
---@field inf_unit_tag any[]
---影响范围
---
---对多大范围内的单位添加光环效果
---@field influence_rng number
---是否影响自己
---
---是否对光环的拥有者添加光环效果
---@field is_influence_self boolean
---ID
---
---魔法效果的ID
---@field key number
---玩家自定义
---@field kv any
---覆盖层数变化
---
---不变会保留旧的魔法效果对象（事件中获取），覆盖会保留新的对象。 
---@field layer_change_of_cover any
---层数上限
---
---魔法效果的最大层数，如果最大层数为1则魔法效果在局内的属性面板中不会显示层数
---@field layer_max number
---最大持续时间
---@field lose_effect_list any
---不透明度
---@field material_alpha number
---材质变化
---
---影响魔法效果携带者的材质
---@field material_change any
---基础材质变色
---@field material_color any
---材质变色强度
---@field material_color_intensity number
---覆盖类型
---
---用于决定单位获得相同的魔法效果时，是否进行覆盖以及如何进行覆盖。
---@field modifier_cover_type any
---效果影响
---
---仅用于标记，用来进行效果分类，在ECA中可以对单位身上同一分类的魔法效果统一处理
---@field modifier_effect any
---图标
---@field modifier_icon any
---效果类别
---
---不同类别的魔法效果将会有
---@field modifier_type any
---名称
---@field name string
---同源覆盖
---
---“同源”指覆盖发生时2个魔法效果的关联技能类型和来源单位相同
---
---当同源覆盖要求为是，2个不同源的魔法效果不会发生覆盖，走不覆盖规则
---@field same_origin_cover boolean
---覆盖护盾变化
---
---护盾发生覆盖时的护盾值的处理方式
---@field shield_change_of_cover any
---护盾类型
---
---通用类可以抵挡物理或法术伤害，物理和法术护盾只能抵挡对应的伤害
---@field shield_type any
---护盾值
---
---护盾可以抵挡的伤害值
---@field shield_value number
---显示图标
---
---勾选后会在局内单位的魔法效果栏中显示该魔法效果
---@field show_on_ui boolean
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list any[]
---编辑器后缀
---@field suffix string
---标签
---@field tags any[]
---目标允许
---
---根据敌我关系决定是否对单位施加光环效果
---@field target_allow any
---覆盖时间变化
---
---若覆盖类型为覆盖时，不变会保留旧的持续时间，覆盖会保留新的持续时间，若覆盖类型为叠加时，规则相反。
---@field time_change_of_cover any
---UID
---
---魔法效果的UID
---@field uid string

---@class Object.BuffOptions
---最大持续时间
---@field attach_model_list? any
---循环周期
---
---每隔多长时间触发一次循环周期到期事件
---@field cycle_time? number
---描述
---@field description? string
---是否死亡时消失
---
---死亡时是否销毁这个魔法效果。永久型的魔法效果不要勾选该选项。
---@field disappear_when_dead? boolean
---最大持续时间
---@field get_effect_list? any
---光环效果
---
---光环会对附近符合条件的单位添加该光环效果
---@field halo_effect? any
---不影响单位标签
---
---不会对拥有指定标签的单位施加光环效果。
---只有满足所有判断条件时，单位才会获得光环效果。
---@field ign_inf_unit_tag? any[]
---不影响单位类型
---
---不会对指定类型的单位施加光环效果。
---只有满足所有判断条件时，单位才会获得光环效果。
---@field ign_inf_unit_type? any
---影响单位标签
---
---会对拥有指定标签的单位施加光环效果。
---只有满足所有判断条件时，单位才会获得光环效果。
---@field inf_unit_tag? any[]
---影响范围
---
---对多大范围内的单位添加光环效果
---@field influence_rng? number
---是否影响自己
---
---是否对光环的拥有者添加光环效果
---@field is_influence_self? boolean
---ID
---
---魔法效果的ID
---@field key? number
---玩家自定义
---@field kv? any
---覆盖层数变化
---
---不变会保留旧的魔法效果对象（事件中获取），覆盖会保留新的对象。 
---@field layer_change_of_cover? any
---层数上限
---
---魔法效果的最大层数，如果最大层数为1则魔法效果在局内的属性面板中不会显示层数
---@field layer_max? number
---最大持续时间
---@field lose_effect_list? any
---不透明度
---@field material_alpha? number
---材质变化
---
---影响魔法效果携带者的材质
---@field material_change? any
---基础材质变色
---@field material_color? any
---材质变色强度
---@field material_color_intensity? number
---覆盖类型
---
---用于决定单位获得相同的魔法效果时，是否进行覆盖以及如何进行覆盖。
---@field modifier_cover_type? any
---效果影响
---
---仅用于标记，用来进行效果分类，在ECA中可以对单位身上同一分类的魔法效果统一处理
---@field modifier_effect? any
---图标
---@field modifier_icon? any
---效果类别
---
---不同类别的魔法效果将会有
---@field modifier_type? any
---名称
---@field name? string
---同源覆盖
---
---“同源”指覆盖发生时2个魔法效果的关联技能类型和来源单位相同
---
---当同源覆盖要求为是，2个不同源的魔法效果不会发生覆盖，走不覆盖规则
---@field same_origin_cover? boolean
---覆盖护盾变化
---
---护盾发生覆盖时的护盾值的处理方式
---@field shield_change_of_cover? any
---护盾类型
---
---通用类可以抵挡物理或法术伤害，物理和法术护盾只能抵挡对应的伤害
---@field shield_type? any
---护盾值
---
---护盾可以抵挡的伤害值
---@field shield_value? number
---显示图标
---
---勾选后会在局内单位的魔法效果栏中显示该魔法效果
---@field show_on_ui? boolean
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list? any[]
---编辑器后缀
---@field suffix? string
---标签
---@field tags? any[]
---目标允许
---
---根据敌我关系决定是否对单位施加光环效果
---@field target_allow? any
---覆盖时间变化
---
---若覆盖类型为覆盖时，不变会保留旧的持续时间，覆盖会保留新的持续时间，若覆盖类型为叠加时，规则相反。
---@field time_change_of_cover? any
---UID
---
---魔法效果的UID
---@field uid? string

---@class Object.Decoration
---挂接物列表
---@field attach_models any
---材质颜色叠加类型
---@field base_color_mod any
---基础材质变色
---@field base_tint_color any
---是否产生阴影
---
---勾选后该装饰物将会计算光照效果形成阴影
---@field cast_shadow boolean
---碰撞盒
---@field collision_box any
---高度图
---@field collision_height any
---碰撞格点
---@field collision_points any
---描述
---@field description string
---效果编辑按钮
---@field effect_button any
---获得特效列表
---@field effect_list any
---@field enable_camera_collision boolean
---遮挡透视
---@field enable_occlusion_perspective boolean
---菲涅尔颜色
---@field fresnel_color any
---菲涅尔强度
---@field fresnel_emissive_color_strength number
---菲涅尔指数
---@field fresnel_exp number
---暂未配置55
---@field icon any
---ID
---
---装饰物的ID
---@field key number
---玩家自定义
---@field kv any
---不透明度
---@field material_alpha number
---材质变化
---@field material_change any
---基础材质变色
---@field material_color any
---材质变色强度
---@field material_color_intensity number
---模型
---@field model any
---模型不透明度
---@field model_opacity number
---名称
---@field name string
---接收贴花
---
---是否允许贴花特效显示在该装饰物上方
---@field receive_decal boolean
---缩放
---@field scale number
---编辑器后缀
---@field suffix string
---UID
---
---装饰物的UID
---@field uid string
---是否启用基础材质变色
---@field use_base_tint_color boolean
---启用菲涅尔效果
---@field use_fresnel boolean
---可通行
---
---勾选后该装饰物如果可通行，将允许单位踩在装饰物上。
---@field use_physics boolean
---启用补光效果
---@field use_virtual_light boolean

---@class Object.DecorationOptions
---挂接物列表
---@field attach_models? any
---材质颜色叠加类型
---@field base_color_mod? any
---基础材质变色
---@field base_tint_color? any
---是否产生阴影
---
---勾选后该装饰物将会计算光照效果形成阴影
---@field cast_shadow? boolean
---碰撞盒
---@field collision_box? any
---高度图
---@field collision_height? any
---碰撞格点
---@field collision_points? any
---描述
---@field description? string
---效果编辑按钮
---@field effect_button? any
---获得特效列表
---@field effect_list? any
---@field enable_camera_collision? boolean
---遮挡透视
---@field enable_occlusion_perspective? boolean
---菲涅尔颜色
---@field fresnel_color? any
---菲涅尔强度
---@field fresnel_emissive_color_strength? number
---菲涅尔指数
---@field fresnel_exp? number
---暂未配置55
---@field icon? any
---ID
---
---装饰物的ID
---@field key? number
---玩家自定义
---@field kv? any
---不透明度
---@field material_alpha? number
---材质变化
---@field material_change? any
---基础材质变色
---@field material_color? any
---材质变色强度
---@field material_color_intensity? number
---模型
---@field model? any
---模型不透明度
---@field model_opacity? number
---名称
---@field name? string
---接收贴花
---
---是否允许贴花特效显示在该装饰物上方
---@field receive_decal? boolean
---缩放
---@field scale? number
---编辑器后缀
---@field suffix? string
---UID
---
---装饰物的UID
---@field uid? string
---是否启用基础材质变色
---@field use_base_tint_color? boolean
---启用菲涅尔效果
---@field use_fresnel? boolean
---可通行
---
---勾选后该装饰物如果可通行，将允许单位踩在装饰物上。
---@field use_physics? boolean
---启用补光效果
---@field use_virtual_light? boolean

---@class Object.Destructible
---@field alive_height_box_data string
---材质颜色叠加类型
---@field base_color_mod any
---基础材质变色
---@field base_tint_color any
---模型缩放
---@field body_size number
---默认角度
---@field collision_box any
---默认角度
---@field collision_points_alive any
---默认角度
---@field collision_points_dead any
---@field dead_height_box_data string
---描述
---@field description string
---死亡销毁延迟
---@field destroy_delay number
---死亡时销毁
---@field destroy_on_die boolean
---死亡特效列表
---@field die_effect_list any
---资源耗尽时死亡
---@field die_on_source_run_out boolean
---持续特效列表
---@field effect_list any
---遮挡透视
---@field enable_occlusion_perspective boolean
---菲涅尔颜色
---@field fresnel_color any
---菲涅尔强度
---@field fresnel_emissive_color_strength number
---菲涅尔指数
---@field fresnel_exp number
---生命值
---@field hp_max number
---图标
---@field icon any
---可被作为技能目标
---@field is_ability_target boolean
---可被攻击
---@field is_attacked boolean
---可被采集
---@field is_collected boolean
---可被选中
---@field is_selected boolean
---ID
---@field key number
---玩家自定义
---@field kv any
---不透明度
---@field material_alpha number
---材质变化
---@field material_change any
---基础材质变色
---@field material_color any
---材质变色强度
---@field material_color_intensity number
---小地图 - 颜色
---@field mini_map_color any
---模型
---@field model any
---模型不透明度
---@field model_opacity number
---名称
---@field name string
---是否可通行
---@field passable boolean
---接收贴花
---@field receive_decal boolean
---小地图 - 显示
---@field show_on_mini_map boolean
---声音事件列表
---@field sound_event_list any[]
---资源名称
---@field source_desc string
---物品类型
---@field source_item any
---资源初始数量
---@field source_nums_init number
---资源最大数量
---@field source_nums_max number
---玩家属性资源
---@field source_player_prop any
---资源回复数量
---@field source_refresh_count number
---资源回复间隔
---@field source_refresh_interval number
---资源类型
---@field source_type any
---编辑器后缀
---@field suffix string
---物品标签
---@field tags any[]
---UID
---@field uid string
---是否启用基础材质变色
---@field use_base_tint_color boolean
---启用菲涅尔效果
---@field use_fresnel boolean
---启用补光效果
---@field use_virtual_light boolean

---@class Object.DestructibleOptions
---@field alive_height_box_data? string
---材质颜色叠加类型
---@field base_color_mod? any
---基础材质变色
---@field base_tint_color? any
---模型缩放
---@field body_size? number
---默认角度
---@field collision_box? any
---默认角度
---@field collision_points_alive? any
---默认角度
---@field collision_points_dead? any
---@field dead_height_box_data? string
---描述
---@field description? string
---死亡销毁延迟
---@field destroy_delay? number
---死亡时销毁
---@field destroy_on_die? boolean
---死亡特效列表
---@field die_effect_list? any
---资源耗尽时死亡
---@field die_on_source_run_out? boolean
---持续特效列表
---@field effect_list? any
---遮挡透视
---@field enable_occlusion_perspective? boolean
---菲涅尔颜色
---@field fresnel_color? any
---菲涅尔强度
---@field fresnel_emissive_color_strength? number
---菲涅尔指数
---@field fresnel_exp? number
---生命值
---@field hp_max? number
---图标
---@field icon? any
---可被作为技能目标
---@field is_ability_target? boolean
---可被攻击
---@field is_attacked? boolean
---可被采集
---@field is_collected? boolean
---可被选中
---@field is_selected? boolean
---ID
---@field key? number
---玩家自定义
---@field kv? any
---不透明度
---@field material_alpha? number
---材质变化
---@field material_change? any
---基础材质变色
---@field material_color? any
---材质变色强度
---@field material_color_intensity? number
---小地图 - 颜色
---@field mini_map_color? any
---模型
---@field model? any
---模型不透明度
---@field model_opacity? number
---名称
---@field name? string
---是否可通行
---@field passable? boolean
---接收贴花
---@field receive_decal? boolean
---小地图 - 显示
---@field show_on_mini_map? boolean
---声音事件列表
---@field sound_event_list? any[]
---资源名称
---@field source_desc? string
---物品类型
---@field source_item? any
---资源初始数量
---@field source_nums_init? number
---资源最大数量
---@field source_nums_max? number
---玩家属性资源
---@field source_player_prop? any
---资源回复数量
---@field source_refresh_count? number
---资源回复间隔
---@field source_refresh_interval? number
---资源类型
---@field source_type? any
---编辑器后缀
---@field suffix? string
---物品标签
---@field tags? any[]
---UID
---@field uid? string
---是否启用基础材质变色
---@field use_base_tint_color? boolean
---启用菲涅尔效果
---@field use_fresnel? boolean
---启用补光效果
---@field use_virtual_light? boolean

---@class Object.Item
---主动技能
---
---使用该物品的时释放的主动技能
---@field attached_ability any
---被动技能
---
---携带该物品时会获得的被动技能
---@field attached_passive_abilities any[]
---自动使用
---
---勾选后获得该物品时会自动使用该物品，如果不满足该物品的主动技能消耗条件则无法拾取
---@field auto_use boolean
---材质颜色叠加类型
---@field base_color_mod any
---基础材质变色
---@field base_tint_color any
---尺寸
---
---物品模型的缩放比例
---@field body_size number
---购买所需资源
---
---从商店里购买这件物品所需要的资源
---@field buy_res_list any[]
---CD组
---
---该物品所在的CD组，物品使用时会使单位持有的相同CD组内所有物品进入使用物品的主动技能冷却
---@field cd_type string
---点击名称面板拾取
---
---开启后，该物品的名字面板可以响应点击，点击后触发拾取道具逻辑。
---@field click_name_pick_up boolean
---合成素材
---
---合成这件物品所需要的材料，拥有所有合成原料后会自动合成该物品
---@field compose_list any[]
---默认充能数
---
---物品创建后的初始充能层数
---@field cur_charge number
---默认堆叠数
---
---物品创建后的初始堆叠层数
---@field cur_stack number
---未拾取时间到期消失
---
---物品在地面上是否会自动销毁
---@field delete_on_discard boolean
---描述
---
---物品的描述和介绍
---@field description string
---开启碰撞
---
---开启后物品与物品之间会发生碰撞，可以防止物品堆叠在一起。碰撞范围设置在游戏规则-通用-物品碰撞范围中。
---@field disable_overlapping boolean
---可以遗弃
---
---玩家是否可以将物品丢弃到地面
---@field discard_enable boolean
---持有者死亡时掉落
---
---物品是否会在携带者死亡时掉落地面
---@field discard_when_dead boolean
---消失时间
---
---掉落在地面上的消失时间
---@field drop_stay_time number
---特效列表
---@field effect_list any
---菲涅尔颜色
---@field fresnel_color any
---菲涅尔强度
---@field fresnel_emissive_color_strength number
---菲涅尔指数
---@field fresnel_exp number
---生命值
---
---物品的生命值，生命值归零则会被销毁
---@field hp_max number
---图标
---
---物品的头像
---@field icon any
---初始库存
---
---物品作为商品时在商店中的初始可购买数
---@field init_stock number
---名称显示方式
---
---鼠标悬浮到物品上时显示的名称样式
---@field item_billboard_type any
---ID
---
---物品的ID
---@field key number
---玩家自定义
---@field kv any
---等级
---
---物品的等级
---@field level number
---不透明度
---@field material_alpha number
---材质变化
---@field material_change any
---材质变化颜色
---@field material_color any
---材质变色强度
---@field material_color_intensity number
---最大库存
---
---物品作为商品时在商店中的最大可购买数
---@field max_stock number
---最大充能数
---
---物品可以设置的最大充能层数
---@field maximum_charging number
---最大堆叠
---
---物品可以叠加的最大堆叠层数。重复获得物品时，在不大于该值的情况下物品会自动堆叠。
---@field maximum_stacking number
---模型
---
---物品掉落在地面的模型
---@field model any
---模型不透明度
---@field model_opacity number
---名称
---@field name string
---名称面板外边距
---
---以名称面板中所有图片计算最大范围，并向外扩展指定的数值
---@field name_margin any
---名称面板不遮挡
---
---开启后，该物品的名称面板将不会与其他开启了该属性的物品的名称面板重叠。
---@field name_not_occlusion boolean
---名称面板偏移
---@field name_offset_based_on_root any
---偏移
---@field offset any
---前置条件
---
---只有满足对应条件之后物品才会在商店中可购买。
---@field precondition_list any[]
---预览面板判定区域
---
---勾选后可预览面板在进行点击判定和堆叠时的区域大小
---@field preview_name_click_range boolean
---预览堆叠效果
---
---勾选后可预览面板在进行平铺堆叠时效果
---@field preview_name_stack boolean
---库存恢复间隔
---
---当前物品作为商品时，商店库存增加的间隔时间
---@field refresh_interval number
---旋转
---@field rotation any
---可以被抵押
---
---是否可以将该物品出售到商店
---@field sale_enable boolean
---出售获得资源
---
---出售到商店时获得的资源
---@field sell_res_list any[]
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list any[]
---堆叠类型
---
---物品的堆叠或者充能逻辑。
---@field stack_type any
---购买开始时间
---
---游戏开始后多长时间才能购买该类物品
---@field start_rft number
---编辑器后缀
---
---在编辑器下显示在名字后面的后缀，在游戏内不显示
---@field suffix string
---物品标签
---
---用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
---@field tags any[]
---UID
---@field uid string
---是否启用基础材质变色
---@field use_base_tint_color boolean
---使用消耗次数
---
---物品是堆叠类型时，每次使用该物品消耗的堆叠层数
---@field use_consume number
---启用菲涅尔效果
---@field use_fresnel boolean
---启用补光效果
---@field use_virtual_light boolean

---@class Object.ItemOptions
---主动技能
---
---使用该物品的时释放的主动技能
---@field attached_ability? any
---被动技能
---
---携带该物品时会获得的被动技能
---@field attached_passive_abilities? any[]
---自动使用
---
---勾选后获得该物品时会自动使用该物品，如果不满足该物品的主动技能消耗条件则无法拾取
---@field auto_use? boolean
---材质颜色叠加类型
---@field base_color_mod? any
---基础材质变色
---@field base_tint_color? any
---尺寸
---
---物品模型的缩放比例
---@field body_size? number
---购买所需资源
---
---从商店里购买这件物品所需要的资源
---@field buy_res_list? any[]
---CD组
---
---该物品所在的CD组，物品使用时会使单位持有的相同CD组内所有物品进入使用物品的主动技能冷却
---@field cd_type? string
---点击名称面板拾取
---
---开启后，该物品的名字面板可以响应点击，点击后触发拾取道具逻辑。
---@field click_name_pick_up? boolean
---合成素材
---
---合成这件物品所需要的材料，拥有所有合成原料后会自动合成该物品
---@field compose_list? any[]
---默认充能数
---
---物品创建后的初始充能层数
---@field cur_charge? number
---默认堆叠数
---
---物品创建后的初始堆叠层数
---@field cur_stack? number
---未拾取时间到期消失
---
---物品在地面上是否会自动销毁
---@field delete_on_discard? boolean
---描述
---
---物品的描述和介绍
---@field description? string
---开启碰撞
---
---开启后物品与物品之间会发生碰撞，可以防止物品堆叠在一起。碰撞范围设置在游戏规则-通用-物品碰撞范围中。
---@field disable_overlapping? boolean
---可以遗弃
---
---玩家是否可以将物品丢弃到地面
---@field discard_enable? boolean
---持有者死亡时掉落
---
---物品是否会在携带者死亡时掉落地面
---@field discard_when_dead? boolean
---消失时间
---
---掉落在地面上的消失时间
---@field drop_stay_time? number
---特效列表
---@field effect_list? any
---菲涅尔颜色
---@field fresnel_color? any
---菲涅尔强度
---@field fresnel_emissive_color_strength? number
---菲涅尔指数
---@field fresnel_exp? number
---生命值
---
---物品的生命值，生命值归零则会被销毁
---@field hp_max? number
---图标
---
---物品的头像
---@field icon? any
---初始库存
---
---物品作为商品时在商店中的初始可购买数
---@field init_stock? number
---名称显示方式
---
---鼠标悬浮到物品上时显示的名称样式
---@field item_billboard_type? any
---ID
---
---物品的ID
---@field key? number
---玩家自定义
---@field kv? any
---等级
---
---物品的等级
---@field level? number
---不透明度
---@field material_alpha? number
---材质变化
---@field material_change? any
---材质变化颜色
---@field material_color? any
---材质变色强度
---@field material_color_intensity? number
---最大库存
---
---物品作为商品时在商店中的最大可购买数
---@field max_stock? number
---最大充能数
---
---物品可以设置的最大充能层数
---@field maximum_charging? number
---最大堆叠
---
---物品可以叠加的最大堆叠层数。重复获得物品时，在不大于该值的情况下物品会自动堆叠。
---@field maximum_stacking? number
---模型
---
---物品掉落在地面的模型
---@field model? any
---模型不透明度
---@field model_opacity? number
---名称
---@field name? string
---名称面板外边距
---
---以名称面板中所有图片计算最大范围，并向外扩展指定的数值
---@field name_margin? any
---名称面板不遮挡
---
---开启后，该物品的名称面板将不会与其他开启了该属性的物品的名称面板重叠。
---@field name_not_occlusion? boolean
---名称面板偏移
---@field name_offset_based_on_root? any
---偏移
---@field offset? any
---前置条件
---
---只有满足对应条件之后物品才会在商店中可购买。
---@field precondition_list? any[]
---预览面板判定区域
---
---勾选后可预览面板在进行点击判定和堆叠时的区域大小
---@field preview_name_click_range? boolean
---预览堆叠效果
---
---勾选后可预览面板在进行平铺堆叠时效果
---@field preview_name_stack? boolean
---库存恢复间隔
---
---当前物品作为商品时，商店库存增加的间隔时间
---@field refresh_interval? number
---旋转
---@field rotation? any
---可以被抵押
---
---是否可以将该物品出售到商店
---@field sale_enable? boolean
---出售获得资源
---
---出售到商店时获得的资源
---@field sell_res_list? any[]
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list? any[]
---堆叠类型
---
---物品的堆叠或者充能逻辑。
---@field stack_type? any
---购买开始时间
---
---游戏开始后多长时间才能购买该类物品
---@field start_rft? number
---编辑器后缀
---
---在编辑器下显示在名字后面的后缀，在游戏内不显示
---@field suffix? string
---物品标签
---
---用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
---@field tags? any[]
---UID
---@field uid? string
---是否启用基础材质变色
---@field use_base_tint_color? boolean
---使用消耗次数
---
---物品是堆叠类型时，每次使用该物品消耗的堆叠层数
---@field use_consume? number
---启用菲涅尔效果
---@field use_fresnel? boolean
---启用补光效果
---@field use_virtual_light? boolean

---@class Object.Projectile
---区分敌我特效显示
---
---开启后可以配置该特效在所属单位的敌人眼中的表现。通常用于处理不同颜色的警示圈或不对敌方显示特效。
---@field async_effect boolean
---描述
---@field description string
---是否立即移除表现
---
---开启后，该投射物被销毁时会立即移除所有表现（适用于没有制作销毁过渡的特效资源）
---@field effect_destroy_way_is_immediately boolean
---敌方特效
---@field effect_foes any
---特效配置
---@field effect_friend any
---图标
---@field icon any
---ID
---
---投射物的ID
---@field key number
---玩家自定义
---@field kv any
---最大持续时间
---
---投射物会在到达最大持续时间后强制删除。摆放在场景上的投射物不会受到限制。
---@field max_duration number
---移动类型
---
---影响可用的可移动通道。
---@field move_channel any
---可移动通道
---
---当投射物作为运动器的运动对象且开启地形阻挡时，作为是否会触发碰撞静态碰撞事件的条件。
---@field move_limitation any
---名称
---@field name string
---是否开启对象池
---
---开启对象池后投射物默认立即移除表现且投射物不会销毁，会以休眠状态进入对象池从而优化性能，重新使用这些对象时自定义属性不会清除，需要手动初始化一遍。
---@field poolable boolean
---是否循环播放
---
---勾选后投射物会在播放完成后重复播放
---@field sfx_loop boolean
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list any[]
---编辑器后缀
---@field suffix string
---标签
---@field tags any[]
---字符串ID
---
---投射物的UID
---@field uid string

---@class Object.ProjectileOptions
---区分敌我特效显示
---
---开启后可以配置该特效在所属单位的敌人眼中的表现。通常用于处理不同颜色的警示圈或不对敌方显示特效。
---@field async_effect? boolean
---描述
---@field description? string
---是否立即移除表现
---
---开启后，该投射物被销毁时会立即移除所有表现（适用于没有制作销毁过渡的特效资源）
---@field effect_destroy_way_is_immediately? boolean
---敌方特效
---@field effect_foes? any
---特效配置
---@field effect_friend? any
---图标
---@field icon? any
---ID
---
---投射物的ID
---@field key? number
---玩家自定义
---@field kv? any
---最大持续时间
---
---投射物会在到达最大持续时间后强制删除。摆放在场景上的投射物不会受到限制。
---@field max_duration? number
---移动类型
---
---影响可用的可移动通道。
---@field move_channel? any
---可移动通道
---
---当投射物作为运动器的运动对象且开启地形阻挡时，作为是否会触发碰撞静态碰撞事件的条件。
---@field move_limitation? any
---名称
---@field name? string
---是否开启对象池
---
---开启对象池后投射物默认立即移除表现且投射物不会销毁，会以休眠状态进入对象池从而优化性能，重新使用这些对象时自定义属性不会清除，需要手动初始化一遍。
---@field poolable? boolean
---是否循环播放
---
---勾选后投射物会在播放完成后重复播放
---@field sfx_loop? boolean
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list? any[]
---编辑器后缀
---@field suffix? string
---标签
---@field tags? any[]
---字符串ID
---
---投射物的UID
---@field uid? string

---@class Object.Unit
---应用科技
---
---单位的可应用科技（会受到该科技的影响）
---@field affect_techs any[]
---敏捷
---@field agility number
---敏捷
---@field agility_grow number
---警戒范围(AI)
---
---单位的警戒范围(AI)
---@field alarm_range number
---允许移动的角度差
---
---当单位转向时，如果转向角度小于该值，则会直接朝目标方向移动；反之会边转向，边移动。
---@field angle_tolerance number
---动画状态名
---@field anim_state_name string
---防御类型
---
---单位的护甲类型，具体效果可在游戏规则中查看
---@field armor_type any
---攻击间隔
---
---单位两次普通攻击之前间隔的秒数，当普攻技能替换为自定义类型时，会使用技能的冷却时间
---@field attack_interval number
---攻击间隔
---
---两次普通攻击之间的间隔时间
---@field attack_interval_grow number
---法术攻击力
---
---单位的法术攻击力
---@field attack_mag number
---法术攻击力
---
---单位的法术攻击力
---@field attack_mag_grow number
---物理攻击力
---
---单位的物理攻击力
---@field attack_phy number
---物理攻击力
---
---单位的物理攻击力
---@field attack_phy_grow number
---攻击范围
---
---单位可以攻击攻击范围内的可见单位，当普攻技能替换为自定义类型时，会使用技能的释放范围
---@field attack_range number
---攻击范围
---
---普通攻击的攻击范围
---@field attack_range_grow number
---攻击速度(%)
---
---单位的攻击速度百分比，局内显示的实际攻速为:1/单位当前普通攻击技能冷却时间*攻击速度
---@field attack_speed number
---攻击速度(%)
---
---攻击速度(倍数)
---@field attack_speed_grow number
---攻击类型
---
---单位的攻击类型，具体效果可在游戏规则中查看
---@field attack_type any
---头顶名称显示方式
---
---影响游戏内物体上方的文本显示内容。
---@field bar_show_name any
---是否显示血条刻度
---
---单位血条上是否会出现刻度线
---@field bar_show_scale boolean
---物品栏
---
---单位的物品栏格数
---@field bar_slot_size number
---材质颜色叠加类型
---@field base_color_mod any
---基础材质变色
---@field base_tint_color any
---头顶名称字体
---
---在单位头顶显示的文字字体
---@field billboard_name_font any
---血条位置偏移
---@field billboard_offset any
---x轴缩放
---@field billboard_scale_x number
---y轴缩放
---@field billboard_scale_y number
---血条样式
---
---该单位在游戏内的血条样式
---@field blood_bar any
---血条显示模式
---
---该单位在游戏内的血条的显示时机
---@field blood_show_type any
---模型缩放
---
---对当前物体模型的缩放倍数，用于调整模型大小。
---@field body_size number
---建造时忽略动态碰撞
---
---使用建造技能建造该单位时，是否忽略其他单位的动态碰撞。
---若需要建造在其他单位脚下（如陷阱类），可勾选该开关。
---@field build_ignore_dyn_collision boolean
---资源消耗
---
---单位作为建筑时建造会消耗的资源
---@field build_res_cost_list any[]
---建造时间（秒）
---@field build_time number
---升级列表
---@field build_upgrade_list any[]
---购买所需资源
---
---单位作为商品的购买所需资源
---@field buy_res_list any[]
---无法反击时会逃跑
---
---当单位受到伤害且自身无法反击时，会向伤害来源的相反方向移动一段距离，仅在警戒状态下生效
---@field can_flee boolean
---取消警戒范围(AI)
---
---单位的取消警戒范围(AI)，敌方离开取消警戒范围后会不再主动攻击敌方
---@field cancel_alarm_range number
---物理主控跳跃高度
---@field cc_jump_height number
---物理主控加速度
---@field cc_move_acc number
---物理主控加速速率
---@field cc_move_acc_rate number
---物理主控跑步速度
---@field cc_run_speed number
---物理主控行走速度
---@field cc_walk_speed number
---冷却缩减(%)
---
---单位技能进入cd时减少部分冷却时间
---@field cd_reduce number
---冷却缩减(%)
---
---单位技能进入cd时减少部分冷却时间
---@field cd_reduce_grow number
---静态碰撞跟随面向
---
---仅对建筑类型单位生效。勾选时，单位改变朝向时会使静态碰撞跟随旋转。
---@field collision_box_turning_enable boolean
---碰撞格点
---@field collision_points any
---动态碰撞半径
---@field collision_radius_2 number
---通用技能
---
---单位的通用技能。在默认UI界面中，会显示在前6个技能栏内，超出的不显示但依然生效。
---@field common_ability_list any[]
---普通攻击
---
---单位的普通攻击，唯一，单位对目标普通攻击时释放的技能
---@field common_atk any
---普攻类型
---
---单位普通攻击的类型，选择自定义需要绑定技能
---@field common_atk_type any
---允许反击范围
---@field counterattack_range number
---暴击率(%)
---
---单位普通攻击有概率造成额外伤害
---@field critical_chance number
---暴击率(%)
---
---单位普通攻击有概率造成额外伤害
---@field critical_chance_grow number
---暴击伤害(%)
---
---发生暴击时，造成的暴击伤害倍数
---@field critical_dmg number
---暴击伤害(%)
---
---发生暴击时，造成的暴击伤害倍数
---@field critical_dmg_grow number
---默认行为
---
---单位默认状态下会执行的行为
---@field default_behaviour_type any
---法术防御力
---
---单位的法术防御力
---@field defense_mag number
---法术防御力
---
---单位的法术防御力
---@field defense_mag_grow number
---物理防御力
---
---单位的物理防御力
---@field defense_phy number
---物理防御力
---
---单位的物理防御力
---@field defense_phy_grow number
---描述
---
---单位的介绍说明，用在编辑器内和游戏内的Tips显示上
---@field description string
---死亡后是否销毁单位
---
---死亡后是否会把单位完全销毁。（会在尸体消失时间结束后进行销毁，销毁后将无法再获取单位相关信息）
---@field destroy_after_die boolean
---死亡
---
---死亡状态下会播放的动画
---@field die_anim string
---圆盘阴影大小
---@field disk_shadow_size number
---伤害减免(%)
---
---百分比降低受到的伤害
---@field dmg_reduction number
---伤害减免(%)
---
---百分比降低受到的伤害
---@field dmg_reduction_grow number
---躲避率(%)
---
---单位躲避其他单位普通攻击的概率
---@field dodge_rate number
---躲避率(%)
---
---单位躲避其他单位普通攻击的概率
---@field dodge_rate_grow number
---掉落物品
---
---单位死亡后会掉落的物品
---@field drop_items_tuple any[]
---寻路碰撞网格边长
---
---碰撞动态半径，每50为1个标准格。
---@field dynamic_collision_r number
---开启物品背包栏
---
---关闭后，单位将不会激活物品栏和背包栏。
---（对不需要背包的单位，关闭此属性可有助于提升地图性能）
---@field enable_item_slots boolean
---开启面向移动模式
---@field enable_strict_facing_mode boolean
---敌方小地图头像
---@field enemy_mini_map_icon any
---所有伤害加成(%)
---
---百分比提高造成的伤害
---@field extra_dmg number
---所有伤害加成(%)
---
---百分比提高造成的伤害
---@field extra_dmg_grow number
---强制显示在小地图
---
---勾选后单位将强制显示在小地图上，无视战争阴影
---@field force_show_on_mini_map boolean
---菲涅尔颜色
---@field fresnel_color any
---菲涅尔强度
---@field fresnel_emissive_color_strength number
---菲涅尔指数
---@field fresnel_exp number
---是否有技能资源条
---
---该单位是否有可以用来释放技能的能量
---@field has_mp boolean
---被治疗效果加成(%)
---
---提高接受治疗时受到的治疗效果
---@field heal_effect number
---被治疗效果提升(%)
---
---提高接受治疗时受到的治疗效果
---@field heal_effect_grow number
---被治疗效果加成(%)
---
---当单位受到治疗效果时，提升治疗量
---@field healing_effect number
---被治疗效果提升(%)
---@field healing_effect_grow number
---@field height_offset number
---英雄技能
---
---单位的英雄技能，可以通过学习升级，每次学习需要消耗一个技能点（升级时获取）。在默认UI界面中，会显示在后6个技能栏内，超出的不显示但依然生效。
---@field hero_ability_list any[]
---命中率(%)
---
---单位普通攻击命中其他单位的概率
---@field hit_rate number
---命中率(%)
---
---单位普通攻击命中其他单位的概率
---@field hit_rate_grow number
---最大生命值
---
---单位的最大生命值
---@field hp_max number
---最大生命值
---
---单位的最大生命值
---@field hp_max_grow number
---生命恢复
---
---单位的每秒生命恢复数值
---@field hp_rec number
---生命恢复
---
---单位的每秒生命恢复数值
---@field hp_rec_grow number
---百分比生命恢复
---
---单位的每秒生命恢复百分比数值
---@field hp_rec_percent number
---百分比生命恢复
---
---单位的每秒生命恢复百分比数值
---@field hp_rec_percent_grow number
---头像
---
---单位在游戏中显示的头像
---@field icon any
---默认状态
---
---默认状态下会播放的动画
---@field idle_anim string
---初始库存
---
---单位作为商品的初始库存
---@field init_stock number
---智力
---@field intelligence number
---智力
---@field intelligence_grow number
---是否应用玩家颜色光圈
---@field is_apply_role_color boolean
---是否在小地图显示
---
---单位是否会在小地图上显示出来
---@field is_mini_map_show boolean
---是否开启透视
---
---勾选后如果该单位被遮挡，会看到该单位的描边
---@field is_open_Xray boolean
---启用圆盘阴影
---@field is_open_disk_shadow boolean
---是否开启描边
---@field is_open_outline_pass boolean
---是否做为商店
---
---开启后单位可以作为商店编辑出售的物品
---@field is_shop boolean
---@field is_x_offset boolean
---@field is_z_offset boolean
---编辑简易普攻
---
---前往表现页编辑详细的简易普攻效果
---@field jump_to_display any
---尸体消失时间
---@field keep_dead_body_time number
---无法移动时仍然保持目标
---
---该字段未勾选时，在目标移动出自身的警戒范围后，且自身不能移动时，会立即开始寻找一个新的攻击目标。多用于定点守卫。
---@field keep_target boolean
---ID
---
---单位的唯一表示
---@field key number
---玩家自定义
---@field kv any
---等级
---
---单位的默认等级
---@field level number
---主属性
---
---英雄单位的主要属性，一般主属性的提升会对英雄有额外加成
---@field main_attr any
---最大平衡角度
---@field max_balance_angle number
---最大库存
---
---单位作为商品的最大库存
---@field max_stock number
---小地图头像
---
---单位在小地图上的头像
---@field mini_map_icon any
---小地图头像缩放
---
---单位在小地图上的头像的缩放
---@field mini_map_icon_scale number
---模型
---
---当前单位所使用的的模型
---@field model any
---离地高度
---
---单位的离地高度
---@field model_height number
---模型不透明度
---@field model_opacity number
---移动类型
---
---单位的移动类型，决定单位究竟是在地面移动还是在空中移动。
---@field move_channel any
---可移动通道
---
---对单位移动类型的补充，决定单位究竟是在哪些通道移动。任意通道被碰撞阻挡该单位均无法通过。
---@field move_limitation any
---移动类型
---
---影响可用的可移动通道。
---@field move_type any
---技能资源条颜色
---
---该单位用来释放技能的能量的颜色
---@field mp_color any
---技能资源名称
---
---该单位用来释放技能的能量的名称
---@field mp_key string
---最大技能资源
---
---单位的最大技能资源
---@field mp_max number
---最大技能资源
---
---单位的最大技能资源
---@field mp_max_grow number
---技能资源恢复
---
---单位的每秒技能资源恢复数值
---@field mp_rec number
---技能资源恢复
---
---单位的每秒技能资源恢复数值
---@field mp_rec_grow number
---名称
---
---当前单位的名称
---@field name string
---是否预览血条
---@field need_preview_billboard boolean
---单位状态
---
---进入游戏时,为单位附加的初始状态
---状态会记录层数，初始为1层。每次添加/移除状态会增加/减少一层。
---@field ori_bits any
---移动速度
---
---单位每秒移动的距离。
---@field ori_speed number
---移动速度
---
---单位每秒移动的距离。
---@field ori_speed_grow number
---描边色值（RGB）
---@field outline_pass_color any
---描边厚度
---@field outline_pass_width number
---隐藏技能
---
---隐藏技能，放在这类技能位中的技能将不会被显示在游戏中。
---@field passive_ability_list any[]
---寻路碰撞额外范围
---@field path_finding_external_size number
---法术穿透
---
---穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag number
---法术穿透
---
---穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag_grow number
---法术穿透(%)
---
---百分比穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag_ratio number
---法术穿透(%)
---
---百分比穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag_ratio_grow number
---物理穿透
---
---穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy number
---物理穿透
---
---穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy_grow number
---物理穿透(%)
---
---百分比穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy_ratio number
---物理穿透(%)
---
---百分比穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy_ratio_grow number
---物理
---@field physics_composite any
---背包栏
---
---单位的背包栏格数
---@field pkg_slot_size number
---是否开启对象池
---
---开启对象池后对象不会销毁，会以休眠状态进入对象池从而优化性能，重新使用这些对象时自定义属性不会清除，需要手动初始化一遍。
---@field poolable boolean
---前置条件
---
---训练、购买、建造该单位的前置条件
---@field precondition_list any[]
---预览血量
---@field preview_billboard_health_value number
---库存恢复间隔
---
---单位作为商品的库存恢复间隔
---@field refresh_interval number
---救援后返回
---@field rescue_finish_return boolean
---求救距离
---@field rescue_seeker_distance number
---求救间隔
---@field rescue_seeker_interval number
---求救类型
---@field rescue_seeker_type any
---救援类型
---@field rescuer_type any
---可研发科技
---
---这些科技，可以在单位身上研发、升级。
---@field research_techs any[]
---经验
---
---该单位被击杀后提供的经验奖励
---@field reward_exp number
---玩家颜色缩放
---@field role_color_scale number
---转身速度
---
---单位的转身速度
---@field rotate_speed number
---出售列表
---
---单位作为商店时的出售列表
---@field sell_list any
---出售获得资源
---
---单位作为商品的出售获得资源
---@field sell_res_list any[]
---是否敌友方显示不同头像
---@field separate_enemy_icon boolean
---出售阵营参数
---@field shop_camp_args any
---商店
---
---可以编辑商店能出售哪些单位与物品，以及允许的出售对象和出售范围
---@field shop_edit any
---商店范围
---@field shop_range number
---出售阵营类型
---@field shop_sell_type any
---悬浮信息显示
---
---开启后鼠标悬浮到单位身上时会显示单位名称和等级的文本框
---@field show_y3_extra_info boolean
---简易普攻
---@field simple_common_atk any
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list any[]
---特殊状态
---
---特殊状态下会播放的动画
---@field special_idle_anim string
---转向时移动速度系数
---
---当单位转向时，移动速度会受到一定的影响。
---@field speed_ratio_in_turn number
---移动动画播放速率系数
---
---单位移动时动画的播放速度
---@field standard_walk_rate number
---购买开始时间
---
---单位作为商品的可购买时间(游戏开始多久后可以购买）
---@field start_rft number
---单位初始状态
---@field state_init any
---单位状态列表
---@field state_list any[]
---力量
---@field strength number
---力量
---@field strength_grow number
---编辑器后缀
---
---给使用编辑器的用户看的备注，无实际作用
---@field suffix string
---标签
---
---用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
---@field tags any[]
---防御塔仇恨持续时间
---@field tower_hatred_duration number
---单位分类
---
---单位类型决定了这类单位的一些特性，包括其可编辑的属性和某些属性的默认值。
---@field type any
---UID
---@field uid string
---是否启用基础材质变色
---@field use_base_tint_color boolean
---启用菲涅尔效果
---@field use_fresnel boolean
---使用简易小地图头像
---
---简易小地图头像的表现为一个小点。简易小地图头像的绘制性能消耗相比普通小地图头像更小，如果地图上会出现大量的该类型单位，建议使用简易小地图头像。
---@field use_simple_mini_map_icon boolean
---启用补光效果
---@field use_virtual_light boolean
---法术吸血(%)
---
---造成法术伤害后可以恢复自身生命值
---@field vampire_mag number
---法术吸血(%)
---
---造成法术伤害后可以恢复自身生命值
---@field vampire_mag_grow number
---物理吸血(%)
---
---造成物理伤害后可以恢复自身生命值
---@field vampire_phy number
---物理吸血(%)
---
---造成物理伤害后可以恢复自身生命值
---@field vampire_phy_grow number
---视野类型
---
---单位与战争迷雾相关的一些属性
---@field view_type any
---夜晚视野
---
---单位在夜晚可以看到（驱散战争迷雾）的范围
---@field vision_night number
---夜晚视野
---@field vision_night_grow number
---白天视野
---
---单位在白天可以看到（驱散战争迷雾）的范围
---@field vision_rng number
---白天视野
---@field vision_rng_grow number
---扇形视野白天夹角
---
---单位在白天拥有的扇形视野夹角。
---@field vision_sector_angle_day number
---@field vision_sector_angle_day_grow number
---扇形视野夜晚夹角
---
---单位在夜晚拥有的扇形视野夹角。
---@field vision_sector_angle_night number
---@field vision_sector_angle_night_grow number
---扇形视野夜晚半径
---
---单位在夜晚拥有的扇形视野半径。
---@field vision_sector_night number
---@field vision_sector_night_grow number
---扇形视野白天半径
---
---单位在白天拥有的扇形视野半径。
---@field vision_sector_rng number
---@field vision_sector_rng_grow number
---真实视野
---
---单位所能侦测到隐身单位的范围
---@field vision_true number
---真实视野
---
---单位所能侦测到隐身单位的范围
---@field vision_true_grow number
---行走
---
---行走状态下会播放的动作
---@field walk_anim string
---@field width_offset number
---悬浮信息显示内容
---@field y3_extra_info_show_type any

---@class Object.UnitOptions
---应用科技
---
---单位的可应用科技（会受到该科技的影响）
---@field affect_techs? any[]
---敏捷
---@field agility? number
---敏捷
---@field agility_grow? number
---警戒范围(AI)
---
---单位的警戒范围(AI)
---@field alarm_range? number
---允许移动的角度差
---
---当单位转向时，如果转向角度小于该值，则会直接朝目标方向移动；反之会边转向，边移动。
---@field angle_tolerance? number
---动画状态名
---@field anim_state_name? string
---防御类型
---
---单位的护甲类型，具体效果可在游戏规则中查看
---@field armor_type? any
---攻击间隔
---
---单位两次普通攻击之前间隔的秒数，当普攻技能替换为自定义类型时，会使用技能的冷却时间
---@field attack_interval? number
---攻击间隔
---
---两次普通攻击之间的间隔时间
---@field attack_interval_grow? number
---法术攻击力
---
---单位的法术攻击力
---@field attack_mag? number
---法术攻击力
---
---单位的法术攻击力
---@field attack_mag_grow? number
---物理攻击力
---
---单位的物理攻击力
---@field attack_phy? number
---物理攻击力
---
---单位的物理攻击力
---@field attack_phy_grow? number
---攻击范围
---
---单位可以攻击攻击范围内的可见单位，当普攻技能替换为自定义类型时，会使用技能的释放范围
---@field attack_range? number
---攻击范围
---
---普通攻击的攻击范围
---@field attack_range_grow? number
---攻击速度(%)
---
---单位的攻击速度百分比，局内显示的实际攻速为:1/单位当前普通攻击技能冷却时间*攻击速度
---@field attack_speed? number
---攻击速度(%)
---
---攻击速度(倍数)
---@field attack_speed_grow? number
---攻击类型
---
---单位的攻击类型，具体效果可在游戏规则中查看
---@field attack_type? any
---头顶名称显示方式
---
---影响游戏内物体上方的文本显示内容。
---@field bar_show_name? any
---是否显示血条刻度
---
---单位血条上是否会出现刻度线
---@field bar_show_scale? boolean
---物品栏
---
---单位的物品栏格数
---@field bar_slot_size? number
---材质颜色叠加类型
---@field base_color_mod? any
---基础材质变色
---@field base_tint_color? any
---头顶名称字体
---
---在单位头顶显示的文字字体
---@field billboard_name_font? any
---血条位置偏移
---@field billboard_offset? any
---x轴缩放
---@field billboard_scale_x? number
---y轴缩放
---@field billboard_scale_y? number
---血条样式
---
---该单位在游戏内的血条样式
---@field blood_bar? any
---血条显示模式
---
---该单位在游戏内的血条的显示时机
---@field blood_show_type? any
---模型缩放
---
---对当前物体模型的缩放倍数，用于调整模型大小。
---@field body_size? number
---建造时忽略动态碰撞
---
---使用建造技能建造该单位时，是否忽略其他单位的动态碰撞。
---若需要建造在其他单位脚下（如陷阱类），可勾选该开关。
---@field build_ignore_dyn_collision? boolean
---资源消耗
---
---单位作为建筑时建造会消耗的资源
---@field build_res_cost_list? any[]
---建造时间（秒）
---@field build_time? number
---升级列表
---@field build_upgrade_list? any[]
---购买所需资源
---
---单位作为商品的购买所需资源
---@field buy_res_list? any[]
---无法反击时会逃跑
---
---当单位受到伤害且自身无法反击时，会向伤害来源的相反方向移动一段距离，仅在警戒状态下生效
---@field can_flee? boolean
---取消警戒范围(AI)
---
---单位的取消警戒范围(AI)，敌方离开取消警戒范围后会不再主动攻击敌方
---@field cancel_alarm_range? number
---物理主控跳跃高度
---@field cc_jump_height? number
---物理主控加速度
---@field cc_move_acc? number
---物理主控加速速率
---@field cc_move_acc_rate? number
---物理主控跑步速度
---@field cc_run_speed? number
---物理主控行走速度
---@field cc_walk_speed? number
---冷却缩减(%)
---
---单位技能进入cd时减少部分冷却时间
---@field cd_reduce? number
---冷却缩减(%)
---
---单位技能进入cd时减少部分冷却时间
---@field cd_reduce_grow? number
---静态碰撞跟随面向
---
---仅对建筑类型单位生效。勾选时，单位改变朝向时会使静态碰撞跟随旋转。
---@field collision_box_turning_enable? boolean
---碰撞格点
---@field collision_points? any
---动态碰撞半径
---@field collision_radius_2? number
---通用技能
---
---单位的通用技能。在默认UI界面中，会显示在前6个技能栏内，超出的不显示但依然生效。
---@field common_ability_list? any[]
---普通攻击
---
---单位的普通攻击，唯一，单位对目标普通攻击时释放的技能
---@field common_atk? any
---普攻类型
---
---单位普通攻击的类型，选择自定义需要绑定技能
---@field common_atk_type? any
---允许反击范围
---@field counterattack_range? number
---暴击率(%)
---
---单位普通攻击有概率造成额外伤害
---@field critical_chance? number
---暴击率(%)
---
---单位普通攻击有概率造成额外伤害
---@field critical_chance_grow? number
---暴击伤害(%)
---
---发生暴击时，造成的暴击伤害倍数
---@field critical_dmg? number
---暴击伤害(%)
---
---发生暴击时，造成的暴击伤害倍数
---@field critical_dmg_grow? number
---默认行为
---
---单位默认状态下会执行的行为
---@field default_behaviour_type? any
---法术防御力
---
---单位的法术防御力
---@field defense_mag? number
---法术防御力
---
---单位的法术防御力
---@field defense_mag_grow? number
---物理防御力
---
---单位的物理防御力
---@field defense_phy? number
---物理防御力
---
---单位的物理防御力
---@field defense_phy_grow? number
---描述
---
---单位的介绍说明，用在编辑器内和游戏内的Tips显示上
---@field description? string
---死亡后是否销毁单位
---
---死亡后是否会把单位完全销毁。（会在尸体消失时间结束后进行销毁，销毁后将无法再获取单位相关信息）
---@field destroy_after_die? boolean
---死亡
---
---死亡状态下会播放的动画
---@field die_anim? string
---圆盘阴影大小
---@field disk_shadow_size? number
---伤害减免(%)
---
---百分比降低受到的伤害
---@field dmg_reduction? number
---伤害减免(%)
---
---百分比降低受到的伤害
---@field dmg_reduction_grow? number
---躲避率(%)
---
---单位躲避其他单位普通攻击的概率
---@field dodge_rate? number
---躲避率(%)
---
---单位躲避其他单位普通攻击的概率
---@field dodge_rate_grow? number
---掉落物品
---
---单位死亡后会掉落的物品
---@field drop_items_tuple? any[]
---寻路碰撞网格边长
---
---碰撞动态半径，每50为1个标准格。
---@field dynamic_collision_r? number
---开启物品背包栏
---
---关闭后，单位将不会激活物品栏和背包栏。
---（对不需要背包的单位，关闭此属性可有助于提升地图性能）
---@field enable_item_slots? boolean
---开启面向移动模式
---@field enable_strict_facing_mode? boolean
---敌方小地图头像
---@field enemy_mini_map_icon? any
---所有伤害加成(%)
---
---百分比提高造成的伤害
---@field extra_dmg? number
---所有伤害加成(%)
---
---百分比提高造成的伤害
---@field extra_dmg_grow? number
---强制显示在小地图
---
---勾选后单位将强制显示在小地图上，无视战争阴影
---@field force_show_on_mini_map? boolean
---菲涅尔颜色
---@field fresnel_color? any
---菲涅尔强度
---@field fresnel_emissive_color_strength? number
---菲涅尔指数
---@field fresnel_exp? number
---是否有技能资源条
---
---该单位是否有可以用来释放技能的能量
---@field has_mp? boolean
---被治疗效果加成(%)
---
---提高接受治疗时受到的治疗效果
---@field heal_effect? number
---被治疗效果提升(%)
---
---提高接受治疗时受到的治疗效果
---@field heal_effect_grow? number
---被治疗效果加成(%)
---
---当单位受到治疗效果时，提升治疗量
---@field healing_effect? number
---被治疗效果提升(%)
---@field healing_effect_grow? number
---@field height_offset? number
---英雄技能
---
---单位的英雄技能，可以通过学习升级，每次学习需要消耗一个技能点（升级时获取）。在默认UI界面中，会显示在后6个技能栏内，超出的不显示但依然生效。
---@field hero_ability_list? any[]
---命中率(%)
---
---单位普通攻击命中其他单位的概率
---@field hit_rate? number
---命中率(%)
---
---单位普通攻击命中其他单位的概率
---@field hit_rate_grow? number
---最大生命值
---
---单位的最大生命值
---@field hp_max? number
---最大生命值
---
---单位的最大生命值
---@field hp_max_grow? number
---生命恢复
---
---单位的每秒生命恢复数值
---@field hp_rec? number
---生命恢复
---
---单位的每秒生命恢复数值
---@field hp_rec_grow? number
---百分比生命恢复
---
---单位的每秒生命恢复百分比数值
---@field hp_rec_percent? number
---百分比生命恢复
---
---单位的每秒生命恢复百分比数值
---@field hp_rec_percent_grow? number
---头像
---
---单位在游戏中显示的头像
---@field icon? any
---默认状态
---
---默认状态下会播放的动画
---@field idle_anim? string
---初始库存
---
---单位作为商品的初始库存
---@field init_stock? number
---智力
---@field intelligence? number
---智力
---@field intelligence_grow? number
---是否应用玩家颜色光圈
---@field is_apply_role_color? boolean
---是否在小地图显示
---
---单位是否会在小地图上显示出来
---@field is_mini_map_show? boolean
---是否开启透视
---
---勾选后如果该单位被遮挡，会看到该单位的描边
---@field is_open_Xray? boolean
---启用圆盘阴影
---@field is_open_disk_shadow? boolean
---是否开启描边
---@field is_open_outline_pass? boolean
---是否做为商店
---
---开启后单位可以作为商店编辑出售的物品
---@field is_shop? boolean
---@field is_x_offset? boolean
---@field is_z_offset? boolean
---编辑简易普攻
---
---前往表现页编辑详细的简易普攻效果
---@field jump_to_display? any
---尸体消失时间
---@field keep_dead_body_time? number
---无法移动时仍然保持目标
---
---该字段未勾选时，在目标移动出自身的警戒范围后，且自身不能移动时，会立即开始寻找一个新的攻击目标。多用于定点守卫。
---@field keep_target? boolean
---ID
---
---单位的唯一表示
---@field key? number
---玩家自定义
---@field kv? any
---等级
---
---单位的默认等级
---@field level? number
---主属性
---
---英雄单位的主要属性，一般主属性的提升会对英雄有额外加成
---@field main_attr? any
---最大平衡角度
---@field max_balance_angle? number
---最大库存
---
---单位作为商品的最大库存
---@field max_stock? number
---小地图头像
---
---单位在小地图上的头像
---@field mini_map_icon? any
---小地图头像缩放
---
---单位在小地图上的头像的缩放
---@field mini_map_icon_scale? number
---模型
---
---当前单位所使用的的模型
---@field model? any
---离地高度
---
---单位的离地高度
---@field model_height? number
---模型不透明度
---@field model_opacity? number
---移动类型
---
---单位的移动类型，决定单位究竟是在地面移动还是在空中移动。
---@field move_channel? any
---可移动通道
---
---对单位移动类型的补充，决定单位究竟是在哪些通道移动。任意通道被碰撞阻挡该单位均无法通过。
---@field move_limitation? any
---移动类型
---
---影响可用的可移动通道。
---@field move_type? any
---技能资源条颜色
---
---该单位用来释放技能的能量的颜色
---@field mp_color? any
---技能资源名称
---
---该单位用来释放技能的能量的名称
---@field mp_key? string
---最大技能资源
---
---单位的最大技能资源
---@field mp_max? number
---最大技能资源
---
---单位的最大技能资源
---@field mp_max_grow? number
---技能资源恢复
---
---单位的每秒技能资源恢复数值
---@field mp_rec? number
---技能资源恢复
---
---单位的每秒技能资源恢复数值
---@field mp_rec_grow? number
---名称
---
---当前单位的名称
---@field name? string
---是否预览血条
---@field need_preview_billboard? boolean
---单位状态
---
---进入游戏时,为单位附加的初始状态
---状态会记录层数，初始为1层。每次添加/移除状态会增加/减少一层。
---@field ori_bits? any
---移动速度
---
---单位每秒移动的距离。
---@field ori_speed? number
---移动速度
---
---单位每秒移动的距离。
---@field ori_speed_grow? number
---描边色值（RGB）
---@field outline_pass_color? any
---描边厚度
---@field outline_pass_width? number
---隐藏技能
---
---隐藏技能，放在这类技能位中的技能将不会被显示在游戏中。
---@field passive_ability_list? any[]
---寻路碰撞额外范围
---@field path_finding_external_size? number
---法术穿透
---
---穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag? number
---法术穿透
---
---穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag_grow? number
---法术穿透(%)
---
---百分比穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag_ratio? number
---法术穿透(%)
---
---百分比穿透敌人法术防御力。先计算固定穿透，再计算百分比穿透
---@field pene_mag_ratio_grow? number
---物理穿透
---
---穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy? number
---物理穿透
---
---穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy_grow? number
---物理穿透(%)
---
---百分比穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy_ratio? number
---物理穿透(%)
---
---百分比穿透敌人物理防御力。先计算固定穿透，再计算百分比穿透
---@field pene_phy_ratio_grow? number
---物理
---@field physics_composite? any
---背包栏
---
---单位的背包栏格数
---@field pkg_slot_size? number
---是否开启对象池
---
---开启对象池后对象不会销毁，会以休眠状态进入对象池从而优化性能，重新使用这些对象时自定义属性不会清除，需要手动初始化一遍。
---@field poolable? boolean
---前置条件
---
---训练、购买、建造该单位的前置条件
---@field precondition_list? any[]
---预览血量
---@field preview_billboard_health_value? number
---库存恢复间隔
---
---单位作为商品的库存恢复间隔
---@field refresh_interval? number
---救援后返回
---@field rescue_finish_return? boolean
---求救距离
---@field rescue_seeker_distance? number
---求救间隔
---@field rescue_seeker_interval? number
---求救类型
---@field rescue_seeker_type? any
---救援类型
---@field rescuer_type? any
---可研发科技
---
---这些科技，可以在单位身上研发、升级。
---@field research_techs? any[]
---经验
---
---该单位被击杀后提供的经验奖励
---@field reward_exp? number
---玩家颜色缩放
---@field role_color_scale? number
---转身速度
---
---单位的转身速度
---@field rotate_speed? number
---出售列表
---
---单位作为商店时的出售列表
---@field sell_list? any
---出售获得资源
---
---单位作为商品的出售获得资源
---@field sell_res_list? any[]
---是否敌友方显示不同头像
---@field separate_enemy_icon? boolean
---出售阵营参数
---@field shop_camp_args? any
---商店
---
---可以编辑商店能出售哪些单位与物品，以及允许的出售对象和出售范围
---@field shop_edit? any
---商店范围
---@field shop_range? number
---出售阵营类型
---@field shop_sell_type? any
---悬浮信息显示
---
---开启后鼠标悬浮到单位身上时会显示单位名称和等级的文本框
---@field show_y3_extra_info? boolean
---简易普攻
---@field simple_common_atk? any
---声音事件列表
---
---可以设置触发指定事件时播放的声音
---@field sound_event_list? any[]
---特殊状态
---
---特殊状态下会播放的动画
---@field special_idle_anim? string
---转向时移动速度系数
---
---当单位转向时，移动速度会受到一定的影响。
---@field speed_ratio_in_turn? number
---移动动画播放速率系数
---
---单位移动时动画的播放速度
---@field standard_walk_rate? number
---购买开始时间
---
---单位作为商品的可购买时间(游戏开始多久后可以购买）
---@field start_rft? number
---单位初始状态
---@field state_init? any
---单位状态列表
---@field state_list? any[]
---力量
---@field strength? number
---力量
---@field strength_grow? number
---编辑器后缀
---
---给使用编辑器的用户看的备注，无实际作用
---@field suffix? string
---标签
---
---用于对物体的分类处理。为单位贴上标签后可以对其进行更方便的关系，例如编写游戏逻辑：杀死所有拥有XX标签的单位
---@field tags? any[]
---防御塔仇恨持续时间
---@field tower_hatred_duration? number
---单位分类
---
---单位类型决定了这类单位的一些特性，包括其可编辑的属性和某些属性的默认值。
---@field type? any
---UID
---@field uid? string
---是否启用基础材质变色
---@field use_base_tint_color? boolean
---启用菲涅尔效果
---@field use_fresnel? boolean
---使用简易小地图头像
---
---简易小地图头像的表现为一个小点。简易小地图头像的绘制性能消耗相比普通小地图头像更小，如果地图上会出现大量的该类型单位，建议使用简易小地图头像。
---@field use_simple_mini_map_icon? boolean
---启用补光效果
---@field use_virtual_light? boolean
---法术吸血(%)
---
---造成法术伤害后可以恢复自身生命值
---@field vampire_mag? number
---法术吸血(%)
---
---造成法术伤害后可以恢复自身生命值
---@field vampire_mag_grow? number
---物理吸血(%)
---
---造成物理伤害后可以恢复自身生命值
---@field vampire_phy? number
---物理吸血(%)
---
---造成物理伤害后可以恢复自身生命值
---@field vampire_phy_grow? number
---视野类型
---
---单位与战争迷雾相关的一些属性
---@field view_type? any
---夜晚视野
---
---单位在夜晚可以看到（驱散战争迷雾）的范围
---@field vision_night? number
---夜晚视野
---@field vision_night_grow? number
---白天视野
---
---单位在白天可以看到（驱散战争迷雾）的范围
---@field vision_rng? number
---白天视野
---@field vision_rng_grow? number
---扇形视野白天夹角
---
---单位在白天拥有的扇形视野夹角。
---@field vision_sector_angle_day? number
---@field vision_sector_angle_day_grow? number
---扇形视野夜晚夹角
---
---单位在夜晚拥有的扇形视野夹角。
---@field vision_sector_angle_night? number
---@field vision_sector_angle_night_grow? number
---扇形视野夜晚半径
---
---单位在夜晚拥有的扇形视野半径。
---@field vision_sector_night? number
---@field vision_sector_night_grow? number
---扇形视野白天半径
---
---单位在白天拥有的扇形视野半径。
---@field vision_sector_rng? number
---@field vision_sector_rng_grow? number
---真实视野
---
---单位所能侦测到隐身单位的范围
---@field vision_true? number
---真实视野
---
---单位所能侦测到隐身单位的范围
---@field vision_true_grow? number
---行走
---
---行走状态下会播放的动作
---@field walk_anim? string
---@field width_offset? number
---悬浮信息显示内容
---@field y3_extra_info_show_type? any
